# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c6976f375a66d69819e0ba21bdbf27a247191e0751317e6786392b525ca893b211e33a46924b82766fb7290b08feec6dd930f52a51203e975366a3e6dbe0738

test:
  secret_key_base: cf036b8d40c26f1ee01048d03edc8532628d43dc5de6b757584a7c039e857db8fe6a3dede8e16f0b5149a9cea876dbcb40ae8281ac0d9fea7347939e53a4a299

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
